name: Kpulk
favicon: null
layout_spectrum: 0.5480833742767572
typography_spectrum: 0.23768751719035208
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.3919682176783681
  lightness: 0.4933983951341361
  saturation: 0.8785585386212915
  rhythmicContrast: 0.9785299629438668
purpose: []
